### ISSUE TITLE
Remove default password

### ISSUE THREAD

**Issue by doridori** [PDDStudio/EncryptedPreferences#1]
Hi, 

I don't see a need in having a default password as shown in https://github.com/PDDStudio/EncryptedPreferences/blob/master/encrypted-preferences/src/main/java/com/pddstudio/preferences/encrypted/EncryptedPreferences.java#L64 with the method

``` java
    private String generateEncryptionString(Context context) {
        return context.getPackageName();
    }
```

This will either 
1. Be accidentally used and render the lib useless
2. Be intentionally used and render the lib useless 

Neither is satisfactory.

This behaviour is not commented anywhere (README or javadocs) afaik. 

I would recommend removing this and making the requirement to supply a password manually - and mention in the README that this needs to not be hardcoded in the app etc.

**Comment by PDDStudio** [comment]
Hey @doridori,

thanks for pointing this out, actually I completely agree with your statement.
The "default" instance creation will be deprecated with the next release version due to security reasons.

This will force developers to specify their own key using the Builder's `withEncryptionPassword(String encryptionPassword)` method.
If no password is set a `RuntimeException` will be thrown.

The documentation (readme & javadocs) will be updated accordingly once the new release is ready.

**Comment by doridori** [comment]
Thats great :)

Glad to be of service

**Comment by PDDStudio** [comment]
Closing this now, the changes I mentioned above are now live with the latest release version 1.2.0
Also the README and JavaDocs have been updated accordingly.

**Comment by doridori** [comment]
Cool - just in case you dont know you can ref this issue in the relevant commit message and it will auto link :)
