### ISSUE TITLE
Remove about_strings.xml please

### ISSUE THREAD

**Issue by Redman1037** [PDDStudio/EncryptedPreferences#6]
I decompiled my apk and found these lines inside strings.xml

   
    <string name="library_EncryptedPreferences_author">Patrick J</string>
    <string name="library_EncryptedPreferences_authorWebsite">http://pddstudio.com/</string>
    <string name="library_EncryptedPreferences_isOpenSource">true</string>
    <string name="library_EncryptedPreferences_libraryDescription">An Android Library to securely read and write encrypted values to your SharedPreferences.</string>
    <string name="library_EncryptedPreferences_libraryName">EncryptedPreferences</string>
    <string name="library_EncryptedPreferences_libraryVersion">1.2.0</string>
    <string name="library_EncryptedPreferences_libraryWebsite">https://github.com/PDDStudio/EncryptedPreferences</string>
    <string name="library_EncryptedPreferences_licenseId">apache_2_0</string>
    <string name="library_EncryptedPreferences_repositoryLink">https://github.com/PDDStudio/EncryptedPreferences</string>

    

Can you please remove these strings , i don't want the hackers to know what library i am using ,because they can easy figure out what encryption it uses . APKs are not 100% secure but i want to give some difficult time for hackers

**Comment by PDDStudio** [comment]
@Redman1037 These Strings are used for automatic detection in [Mike Penz's AboutLibraries](https://github.com/mikepenz/AboutLibraries).
I can understand your considerations regarding people who might reverse engineer your APK and find those strings, but nevertheless - this library is licensed under Apache 2.0 License – and therefore you  *have to give proper credits for it* anyways.

In addition, these strings might just provide information about **which library** (aka the encryption algorithm) you're using, **not the actual password itself**. (which is the important part of data de/encryption).

I'm closing this now as because removing those Strings is not in purpose of an Apache-licensed project. Furthermore, I'd also recommend you to dig a bit deeper into the purposes/requirements for various OpenSource License types before violating any terms once your project is published.

Anyways, thank you for using `EncryptedPreferences`!

Best Regards
